### ISSUE TITLE
Deleted movies not being removed from dbM.json

### ISSUE THREAD

**Issue by KeithGraber** [pastapojken/Myflix#10]
Hello!

What is the proper process to delete movies?

I removed the movie file from Movies, ran 'buildDB.sh 1', followed by 'buildHTML.sh 1', but the deleted movie is still listed in dbM.json and therefore in Movie.html

In the past I've deleted both Movie.html and dbM.json and rebuilt dbM.json, but I'm wondering if I'm doing something incorrect.

Thanks!

**Comment by farfalleflickan** [comment]
Hi!

Technically there isn't one, the idea is you open up dbM.json, find the movie you want to delete and remove that json object.

I've thought about different implementations in the past but chosen against it simply because it has felt like too little pay off for the (admittedly minimal) effort. As the code is structured now, it would also be basically as fast as just deleting dbM.json and re-building it.   

I've been actually working on a complete re-implementation of Myflix, which will 'automagically' update/remove movies. It's written in C and by my benchmarks so far it's 20 times faster. I just have to get around to finish it, there's only the boring stuff left...

**Comment by KeithGraber** [comment]
Thanks for the feedback that I've not missed something obvious (which happens for more frequently than I'd like to admit :-) ).

For now I'll just continue deleting dbM.json, and I see I need to empty the screenshots and MoImag directories since old thumbnails are still there.

It's exciting to hear about a new version!  Can't wait to give it a spin when it's ready!

Have a great day!
