### ISSUE TITLE
Feature Request: Use existing metadata

### ISSUE THREAD

**Issue by UnR34L** [pastapojken/Myflix#3]
I already have a pretty OCD media library, would it be possible to use exiting nfo files and artwork instead of using TMDB?

I'm using the recommended conventions for Kodi/Plex

/Movies/Title (Year)/
>Title (Year).mp4
>Title (Year).nfo
>Title (Year).eng.srt
>folder.jpg
>fanart.jpg

**Comment by farfalleflickan** [comment]
It would definitely be possible, although perhaps not super simple. It's a good feature though.
I can't give an exact timeline for when it will be done, but i will start working on it as soon as i have time ;) 
Thanks for the suggestion!

**Comment by farfalleflickan** [comment]
Sorry for the incredibly long wait, your feature has been implemented!  :)
It should be working, although I'm a bit unsure about the TV show side of things...
I followed the example files in the Kodi wiki (http://kodi.wiki/view/NFO_files), get back to me if something breaks or is weird or something :)

**Comment by UnR34L** [comment]
I can't get this to work.

I had to install 'libxml2-utils' and 'jq' before it would run (I can't see any dependency in the README.md or wiki), but that was the easy part.

I had to use the full path to the config file in 'nfoToDBs.sh' (line 11) and 'parseMnfo.sh' (line 10) you probably know a better way to fix that.

Then I ended up with "readlink: missing operand"

In the .nfo I used, it uses a link to the poster not a path to a file, I think that's why it's having problems.

Also, hoping that it uses the poster images already present, folder.jpg.

I didnt make any changes to the config file, tree looks like this if its any help.

```
root@debian:/var/www/html/Myflix# tree
.
├── css
│   ├── movie.css
│   └── tv.css
├── dbM.json
├── dbTV.json
├── js
│   ├── Mcript.js
│   └── TVcript.js
├── LICENSE.md
├── Movies
│   └── Ratatouille.(2007)
│       ├── fanart.jpg
│       ├── folder.jpg
│       ├── Ratatouille.(2007).mp4
│       └── Ratatouille.(2007).nfo
├── Movies.html
├── README.md
├── scripts
│   ├── bMhtml.sh
│   ├── bTVhtml.sh
│   ├── bTVShow.sh
│   ├── buildDBs.sh
│   ├── buildHtml.sh
│   ├── config.cfg
│   ├── fixFile.sh
│   ├── getMid.sh
│   ├── getMposter.sh
│   ├── getTVid.sh
│   ├── getTVposter.sh
│   ├── nfoToDBs.sh
│   ├── parseMfilename.sh
│   ├── parseMnfo.sh
│   ├── parseTVfilename.sh
│   └── parseTVnfo.sh
├── TV
│   └── FamilyGuy
│       ├── banner.jpg
│       ├── fanart.jpg
│       ├── poster.jpg
│       ├── season01-banner.jpg
│       ├── season01-poster.jpg
│       ├── Season.1
│       │   ├── FamilyGuy.S16E01.jpg
│       │   ├── FamilyGuy.S16E01.mp4
│       │   └── FamilyGuy.S16E01.nfo
│       ├── theme.mp3
│       └── tvshow.nfo
└── TV.html

8 directories, 40 files
```

**Comment by farfalleflickan** [comment]
The dependencies are listed under requirements ( which perhaps i should rename for clarity, thanks for the heads up) in the README.

You shouldn't need to rename the `. config.cfg`, the `.` is a "shortcut" for the `source` command and since the config file is supposed to be in the same folder as the scripts the path should be right. 
I'm fairly sure it's an issue of reading rights or missing config file (or something of the sort), as it is `relPath=$(readlink -f ${MoviesPath});` that is giving you issues ( the MoviesPath is unset and i forgot to add the default value in case `. config.cfg` fails, which makes readlink crash). I will add some checks for that so it's clearer in the future (once i get back to my main machine in a week or so). 

Regarding the poster, based on the `.nfo`s on the Kodi wiki I figured that the smartest way to go about it was fetch the first value of the `thumb` tag (wether it's a path or an url is irrelevant ), I think I'm gonna make it more "flexible" by making it user definable with a variable.

Anyway I committed a minimal fix so it should be running now :) Hope it works and happy new year!
