### ISSUE TITLE
Non TV Shows Movies

### ISSUE THREAD

**Issue by 12nick12** [pastapojken/Myflix#5]
Is there any way to have it present just a random file structure that isn't tv or movies?

**Comment by farfalleflickan** [comment]
I'm not quite sure I understand the question, but in theory yes, as long as they are mp4 video files. Let's say that you have a bunch of mp4 of your vacation or something. You could simply put them all in a folder that you called "movies" and the script would build the database and corresponding html page. The only "problem" is that the html displays movie posters, so you would have to provide some kind of image to replace it in order to make the html actually usable. So, in short, yes there is, you will just have to provide an image to display as the video's "poster" in order to make it all usable.
Also, you might want to disable all metadata fetching, to make it all faster & easier
