### ISSUE TITLE
Video filenames with spaces break buildDBs.sh

### ISSUE THREAD

**Issue by KeithGraber** [pastapojken/Myflix#7]
Hello

Video filenames that have spaces are not processed correctly and the resulting entries in the database files are broken.

When using the "Home Movies" option this also produces a listing of the filename with no video to view (makes sense since there isn't a correct entry in the database).  I haven't tried with regular Movies or TV Shows.

Thanks!

**Comment by farfalleflickan** [comment]
Hi again!
Ah! Yes, spaces break... everything, or almost. Technically it would be solvable but the pain of making sure nothing ever breaks with every possible combination is greater than just changing out the spaces in the file names with dots. 
I'm actually inclined to not "fix" this, unless it's really really needed.
Otherwise you could also try with modifying the regexes in the config (there's a "regexHM" for home movies) into something that uses spaces, but I actually think something else might still break later on in the program.

**Comment by KeithGraber** [comment]
OK, maybe I'll play with the regexes.  Not a huge deal for me.  I have a couple of videos with filenames that contain spaces that I can easily change.

Maybe on the front page or in the Wiki this should be stated?

**Comment by farfalleflickan** [comment]
Ok, good then, saves me some work :D 
It's in the wiki, under "Hard coded stuff & special mentions", will make it clearer tho ;)
